integra/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls'))
]

website/urls.py
from django.urls import path, include
from website.views import index, cadastro_candidato, cadastro_empresa, login, cadastro_cv, pagina_candidato, pagina_empresa, informacao_candidato


app_name = 'curriculos'

urlpatterns = [
    path('', index),
    path('login', login),
    path('cadastro_empresa', cadastro_empresa),
    path('cadastro_candidato', cadastro_candidato),
    path('cadastro_cv', cadastro_cv),
    path('pagina_candidato', pagina_candidato),
    path('pagina_empresa', pagina_empresa),
    path('candidato/<int:id>', informacao_candidato, name ='curriculo')
]

website/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Candidato(models.Model):

    GENEROS = (
        ('F','Feminino'),
        ('M','Masculino'),
        ('O','Outro'),
    )

    PAIS = (
	('AFE', 'Afeganistão'),
	('ADS', 'África do Sul'),
	('ALB','Albânia'),
	('ALE', 'Alemanha'),
    ('AND', 'Andorra'),
	('ANGO','Angola'),
	('ANG', 'Anguilla'),
	('AH','Antilhas Holandesas'),
	('ANT', 'Antárctida'),
	('AB', 'Antígua e Barbuda'),
	('ARG','Argentina'),
	('ARGE','Argélia'),
	('ARM', 'Armênia'),
	('ARU', 'Aruba'),
	('AS', 'Arábia Saudita'),
	('AUS', 'Austrália'),
	('AUST', 'Áustria'),
	('AZE', 'Azerbaijão'),
	('BAH', 'Bahamas'),
	('BAHR', 'Bahrein'),
	('BANG', 'Bangladesh'),
	('BARB','Barbados'),
	('BEL', 'Belize'),
	('BEN', 'Benim'),
	('BER', 'Bermudas'),
	('BIE', 'Bielorrússia'),
	('BOL', 'Bolívia'),
	('BOT', 'Botswana'),
	('BRU','Brunei'),
	('BUL','Bulgária'),
	('BURK','Burkina Faso'),
	('BURU','Burundi'),
	('BUT','Butão'),
	('BEL','Bélgica'),
	('BOSH','Bósnia e Herzegovina'),
	('CB','Cabo Verde'),
	('CAMA','Camarões'),
	('CAMB','Camboja'),
	('CAN','Canadá'),
	('CAT','Catar'),
	('CAZ','Cazaquistão'),
	('CHA','Chade'),
	('CHIL','Chile'),
	('CHIN','China'),
	('CHI','Chipre'),
	('COL','Colômbia'),
	('COM','Comores'),
	('CDN','Coreia do Norte'),
	('CDS','Coreia do Sul'),
	('CDM','Costa do Marfim'),
	('CR','Costa Rica'),
	('CRO','Croácia'),
	('CBA','Cuba'),
	('DIN','Dinamarca'),
	('DJI','Djibouti'),
	('DOM','Dominica'),
	('EGI','Egito'),
	('ES','El Salvador'),
	('EMA','Emirados Árabes Unidos'),
	('EQU','Equador'),
	('ERI','Eritreia'),
	('ESC','Escócia'),
	('ESL','Eslováquia'),
	('ESLOVE','Eslovênia'),
	('ESP','Espanha'),
	('EFM','Estados Federados da Micronésia'),
	('EUA', 'Estados Unidos'),
	('EST','Estônia'),
	('ETI','Etiópia'),
	('FIJ','Fiji'),
	('FIL','Filipinas'),
	('FIN','Finlândia'),
	('FRA','França'),
	('GAB','Gabão'),
	('GA','Gana'),
	('GE','Geórgia'),
	('GIB','Gibraltar'),
	('GRA','Granada'),
	('GRO', 'Gronelândia'),
	('GRE','Grécia'),
	('GUAD','Guadalupe'),
	('GUAM', 'Guam'),
	('GUAT','Guatemala'),
	('GUE','Guernesei'),
	('GUI','Guiana'),
	('GUIF','Guiana Francesa'),
	('GUE','Guiné'),
	('GUEEQ','Guiné Equatorial'),
	('GUIB','Guiné-Bissau'),
	('GAM','Gâmbia'),
	('HAI','Haiti'),
	('HON','Honduras'),
	('HK','Hong Kong'),
	('HUN','Hungria'),
	('IB','Ilha Bouvet'),
	('IM','Ilha de Man'),
	('IN','Ilha do Natal'),
	('IHIM','Ilha Heard e Ilhas McDonald'),
	('INOR','Ilha Norfolk'),
	('ICAY','Ilhas Cayman'),
	('ICO','Ilhas Cocos(Keeling)'),
    ('ICOOK','Ilhas Cook'),
	('IFE','Ilhas Feroé'),
	('IGSSS','Ilhas Geórgia do Sul e Sandwich do Sul'),
	('IMA', 'Ilhas Malvinas'),
	('IMAR','Ilhas Marshall'),
	('IMDEU', 'Ilhas Menores Distantes dos Estados Unidos'),
	('IRAQ','Iraque'),
	('IS','Ilhas Salomão'),
	('IVA','Ilhas Virgens Americanas'),
	('IVB','Ilhas Virgens Britânicas'),
	('IAL','Ilhas Åland'),
	('INDO','Indonésia'),
	('ING','Inglaterra'),
	('INDI','Índia'),
	('IRN','Irlanda do Norte'),
	('IRL','Irlanda'),
	('IRA','Irã'),
	('ISL','Islândia'),
	('ISR','Israel'),
	('ITA','Itália'),
	('IEM','Iêmen'),
	('JAM','Jamaica'),
	('JAP','Japão'),
	('JER','Jersey'),
	('JOR','Jordânia'),
	('KIR','Kiribati'),
	('KUW','Kuwait'),
	('LAO','Laos'),
	('LES','Lesoto'),
	('LET','Letônia'),
	('LIB','Libéria'),
	('LIE','Liechtenstein'),
	('LIT','Lituânia'),
	('LUX','Luxemburgo'),
	('LIBA','Líbano'),
	('LIBI','Líbia'),
	('MAC','Macau'),
	('MAC','Macedônia'),
	('MAD','Madagáscar'),
	('MALA','Malawi'),
	('MALD','Maldivas'),
	('MALI','Mali'),
	('MALTA','Malta'),
	('MALAS','Malásia'),
	('MARIS','Marianas Setentrionais'),
	('MARR','Marrocos'),
	('MART','Martinica'),
	('MAUR','Mauritânia'),
	('MAURI','Maurícia'),
	('MAYO','Mayotte'),
	('MOL','Moldávia'),
	('MON','Mongólia'),
	('MONT','Montenegro'),
	('MONTS','Montserrat'),
	('MOÇ','Moçambique'),
	('MYA','Myanmar'),
	('MEX','México'),
	('MON','Mônaco'),
	('NAM','Namíbia'),
	('NAU','Nauru'),
	('NEP','Nepal'),
	('NIC','Nicarágua'),
	('NIG','Nigéria'),
	('NIU','Niue'),
	('NOR','Noruega'),
	('NC','Nova Caledônia'),
	('NZ','Nova Zelândia'),
	('NIG','Níger'),
	('OMA','Omã'),
	('PAL','Palau'),
	('PALE','Palestina'),
	('PAN','Panamá'),
	('PNG','Papua-Nova Guiné'),
	('PAQ','Paquistão'),
	('PAR','Paraguai'),
	('PDG','País de Gales'),
	('PB','Países Baixos'),
	('PE','Peru'),
	('PIT','Pitcairn'),
	('PF','Polinésia Francesa'),
	('POL','Polônia'),
	('PR','Porto Rico'),
	('POR','Portugal'),
	('QUI','Quirguistão'),
	('QUE','Quênia'),
	('RU','Reino Unido'),
	('RCA','República Centro-Africana'),
	('RC','República Checa'),
	('RDC','República Democrática do Congo'),
	('RCO','República do Congo'),
	('RD','República Dominicana'),
	('REU','Reunião'),
	('ROM','Romênia'),
	('RUA','Ruanda'),
	('RUS','Rússia'),
	('SAA','Saara Ocidental'),
	('SM','Saint Martin'),
	('SB','Saint-Barthélemy'),
	('SPM','Saint-Pierre e Miquelon'),
	('SAM','Samoa Americana'),
	('SA','Samoa'),
	('SHATC','Santa Helena, Ascensão e Tristão da Cunha'),
	('SL','Santa Lúcia'),
	('SEN','Senegal'),
	('SLE','Serra Leoa'),
	('SEY','Seychelles'),
	('SIN','Singapura'),
	('SOM','Somália'),
	('SRI','Sri Lanka'),
	('SUAZ','Suazilândia'),
	('SUD','Sudão'),
	('SUR','Suriname'),
	('SUE','Suécia'),
	('SUI','Suíça'),
	('SVA','Svalbard e Jan Mayen'),
	('SCN','São Cristóvão e Nevis'),
	('SM','São Marino'),
	('STP','São Tomé e Príncipe'),
	('SVG','São Vicente e Granadinas'),
	('SERV','Sérvia'),
	('SIR','Síria'),
	('TAD','Tadjiquistão'),
	('TAI','Tailândia'),
	('TAIW','Taiwan'),
	('TAN','Tanzânia'),
	('TAAF','Terras Austrais e Antárticas Francesas'),
	('TBOI','Território Britânico do Oceano Índico'),
	('TL','Timor-Leste'),
	('TOG','Togo'),
	('TON','Tonga'),
	('TOQ','Toquelau'),
	('TRI','Trinidad e Tobago'),
	('TUN','Tunísia'),
	('TUR','Turcas e Caicos'),
	('TURQ','Turquemenistão'),
	('TURQUI','Turquia'),
	('TUV','Tuvalu'),
	('UCR','Ucrânia'),
	('UGA','Uganda'),
	('URU','Uruguai'),
	('UZB','Uzbequistão'),
	('VAN','Vanuatu'),
	('VAT','Vaticano'),
	('VEN','Venezuela'),
	('VIET','Vietname'),
	('WAF','Wallis e Futuna'),
	('ZIM','Zimbabwe'),
	('ZAM','Zâmbia')
    )

    nome = models.CharField(
        max_length=255,
        verbose_name='Nome'
    )

    sobrenome = models.CharField(
        max_length=255,
        verbose_name='Sobrenome'
    )

    rne = models.CharField(
        max_length=255,
        verbose_name='Rne'
    )

    pais_de_origem = models.CharField(
        max_length=255,
        verbose_name='País de Origem',
        choices = PAIS,
		null= True
    )

    data_nascimento = models.DateField()

    genero = models.CharField(
        max_length=255,
        verbose_name='Gênero',
        choices = GENEROS
    )

    senha = models.CharField(
        max_length=255,
        verbose_name='Senha'
    )

    email = models.EmailField(
        max_length=255,
        verbose_name='E-mail'
    )

    telefone = models.CharField(
        max_length=10,
        verbose_name='Telefone',
        null= True
    )

    celular = models.CharField(
        max_length=11,
        verbose_name='Celular',
        null= True
    )
	
    data_de_criacao = models.DateField(auto_now=True)
    ativo = models.BooleanField(default=True)

    def __str__(self):
        return self.nome + ' ' + self.sobrenome

	# def pais_verbose(self)
		# return dict(Scoop.PAIS)[self.pais_de_origem]

    


class Curriculo(models.Model):

	AREAS = (
        ('CMC', 'Comunicação'),
        ('SD', 'Saúde'),
        ('TEC', 'Tecnologia'),
        ('FIN', 'Financeiro'),
        ('ADM', 'Administração'),
        ('RH', 'RH'),
        ('JUR', 'Jurídica'),
        ('OTR', 'Outro')
    )

	ESCOLARIDADE = (
        ('EFI', 'Ensino Fundamental Incompleto'),
        ('EFC', 'Ensino Fundamental Cursando'),
        ('EFCO', 'Ensino Fundamental Completo'),
        ('EMI', 'Ensino Médio Incompleto'),
        ('EMC', 'Ensino Médio Cursando'),
        ('EMCO', 'Ensino Médio Completo'),
        ('ESI', 'Ensino Superior Incompleto'),
        ('ESC', 'Ensino Superior Cursando'),
        ('ESCO', 'Ensino Superior Completo'),
        ('P', 'Pós Graduação'),
        ('M', 'Mestrado'),
        ('D', 'Doutorado')
    )

	IDIOMA = (
		('INGLES', 'Inglês'),
		('ESPANHOL', 'Espanhol'),
		('FRANCES', 'Francês'),
		('OTR', 'Outro')
	)

	candidato = models.ForeignKey(
        Candidato, on_delete=None,
		null=True,
		verbose_name = 'Candidato',
    )

	apresentacao = models.TextField(
		verbose_name = 'Apresentação',
        null=True,
        blank=True
    )

	area = models.CharField(
        verbose_name = 'Áreas',
        choices = AREAS,
        max_length=255,
        null= True
    )

	area_outros = models.CharField(
        null= True,
        blank=True,
        max_length=22,
        verbose_name = 'Caso outra, qual?'
    )

	formacao = models.TextField(
		null= True,
        verbose_name="Formação",
        blank=True
    )

	idioma = models.TextField(
		null= True,
		choices = IDIOMA,
        verbose_name= "Idioma",
        blank=True
    )

	idioma_outros = models.CharField(
        null= True,
        blank=True,
        max_length=22,
        verbose_name = 'Caso outra, qual?'
    )

	historico = models.TextField(
        verbose_name="Histórico Profissional",
        blank=True
    )

	escolaridade = models.CharField(
        verbose_name = 'Escolaridade',
        choices = ESCOLARIDADE,
        max_length=255,
        default='SOME STRING'
    )

	ativo = models.BooleanField(
		default=True
	)
	def get_absolute_url(self):
		return reverse('curriculos:curriculo', kwargs={'id': self.id})
    # slug = models.SlugField(max_length=100)

	def __str__(self):
		return 'Curriculo de '

class Empresa(models.Model):
    razao_social = models.CharField(
        max_length = 255,
        verbose_name = 'Razão Social'
    )

    email = models.EmailField(
        max_length=255,
        verbose_name='E-mail'
    )

    cnpj = models.CharField(
        max_length = 14,
        verbose_name = 'CNPJ'
    )

    senha = models.CharField(
        max_length = 255,

website/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from website.models import Empresa, Candidato, Curriculo

# Create your views here.

def index(request):
    return render(request, 'index.html')


def login(request):
    # função para deixar dois logins em uma unica index
    contexto = {}
    # verifica se o metodo é POST
    if request.method == 'POST':
        # verifica se o botão de login clicado pertence ao formulario de usuario
        if request.POST.get('submit') == 'ACESSAR CANDIDATO':
            # pega as informações do candidato apartir dos dados informados no formulario
            email_candidato = request.POST.get('email_candidato')
            senha_candidato = request.POST.get('senha')
            candidato = Candidato.objects.filter(email=email_candidato, senha=senha_candidato).first()
            # caso os dados forem invalidos/não existirem devolve uma mensagem de erro
            if candidato is None:
                contexto = {'msg':'login ou senha incorreto'}
            # caso tudo estiver correto redirecionaria para pagina em que o candidato altera suas informações
            # pagina inexistente
            else:
                contexto = {'candidato':candidato}
                return render(request,'cadastro_cv.html',contexto)


        # verifica se o botão de login clicado pertence ao formulario de empresa
        elif request.POST.get('submit') == 'ACESSAR EMPRESA':
            email_empresa = request.POST.get('email_empresa')
            senha_empresa = request.POST.get('senha')
            empresa = Empresa.objects.filter(email=email_empresa, senha=senha_empresa).first()
            if empresa is None:
                contexto = {'msg':'login ou senha incorreto'}
            else:
                candidatos = Candidato.objects.filter(ativo=True).all()
                curriculos = Curriculo.objects.filter(ativo=True).all()
                contexto = {'empresa':empresa, 'candidatos': candidatos, 'curriculos':curriculos}
                return render(request, 'pagina_empresa.html', contexto)
    return render(request, 'login.html',contexto)



def cadastro_empresa(request):
    if request.method == 'POST':
        empresa = Empresa()
        empresa.razao_social = request.POST.get('razao_social')
        empresa.cnpj = request.POST.get('cnpj')
        empresa.senha = request.POST.get('senha')
        empresa.email = request.POST.get('email')
        empresa.save()
        return render(request, 'login.html')

    return render(request, 'cadastro_empresa.html')

def cadastro_candidato(request):
    if request.method == 'POST':
        candidato = Candidato()
        candidato.nome = request.POST.get('nome')
        candidato.sobrenome = request.POST.get('sobrenome')
        candidato.rne = request.POST.get('rne')
        candidato.pais_de_origem = request.POST.get('pais_de_origem')
        candidato.data_nascimento = request.POST.get('data_nascimento')
        candidato.genero = request.POST.get('genero')
        candidato.senha = request.POST.get('senha')
        candidato.email = request.POST.get('email')
        candidato.telefone = request.POST.get('telefone')
        candidato.celular = request.POST.get('celular')
        candidato.save()
        return render(request, 'login.html')
    return render(request, 'cadastro_candidato.html')


def cadastro_cv(request):   
    if request.method == 'POST':
        email_candidato = request.POST.get('email')
        candidato = Candidato.objects.filter(email=email_candidato).first()
        if candidato is not None:
            curriculo = Curriculo()
            curriculo.candidato = candidato
            curriculo.apresentacao = request.POST.get('apresentacao')
            curriculo.area = request.POST.get('area')
            curriculo.area_outros = request.POST.get('area_outros')
            curriculo.escolaridade = request.POST.get('escolaridade')
            curriculo.formacao = request.POST.get('formacao')
            curriculo.idioma = request.POST.get('idioma')
            curriculo.idioma_outros = request.POST.get('idioma_outros')
            curriculo.historico = request.POST.get('historico')
            curriculo.save()
            return redirect('/cadastro_cv')
    return render(request, 'index.html')

def pagina_candidato(request):
    candidatos = Candidato.objects.filter(ativo=True).all()
    contexto = {"candidatos":candidatos}
    return render(request, 'pagina_candidato.html',contexto)

# view para retornar lista de candidatos
def pagina_empresa(request):
    candidatos = Candidato.objects.filter(ativo=True).all()
    contexto = {"candidatos":candidatos}
    return render(request, 'pagina_empresa.html', contexto)

# view para retornar informações do candidato
def informacao_candidato(request, id):
    curriculo = get_object_or_404(Curriculo, id=id)
    contexto = {'curriculo':curriculo}
    return render(request, 'informacao_candidato.html', contexto)

website/templates/cadastro_cv.html
{% extends 'shared/layout.html' %}
{% block conteudo %}
{% if candidato is None %}
    <h1>Ops, você precisa se cadastrar</h1>
    <p>
        <a href="/">clique aqui para se cadastrar</a>
    </p>
{% else %}
<div class="area-centro">
    
    
    <h1>Preencha aqui seu currículo {{candidato.nome}}</h1>
<div class="area-form ">

<form action="/cadastro_cv" method="POST">
    {% csrf_token %}
    <input type="hidden" name="email" value="{{candidato.email}}">
    <div class="area">
        <label>Area</label>
        <select name="area" id="opcoesarea" onchange="optionCheck()">
            <option value="CMD">Comunicação</option>
            <option value="SD">Saúde</option>
            <option value="TEC">Tecnologia</option>
            <option value="FIN">Financeiro</option>
            <option value="ADM">Adminstração</option>
            <option value="RH">Recursos Humanos</option>
            <option value="JUR">Jurídica</option>
            <option value="OTR">Outro</option>
        </select>

    </div>

    <div class="area_outros">
        <label>Outros</label>
        <input type="text" name="area_outros">
    </div>
    <div class="apresentacao">
        <label>Apresentacao</label>
        <input type="text" name="apresentacao">
    </div>
    <div class="escolaridade">
        <label>Nível de Escolaridade</label>
        <select name="escolaridade">
            <option value="EFI">Ensino Fundamental Incompleto</option>
            <option value="EFC">Ensino Fundamental Cursando</option>
            <option value="EFCO">Ensino Fundamental Completo</option>
            <option value="EMI">Ensino Médio Incompleto</option>
            <option value="EMC">Ensino Médio Cursando</option>
            <option value="EMCO">Ensino Médio Completo</option>
            <option value="ESI">Ensino Superior Incompleto</option>
            <option value="ESC">Ensino Superior Cursando</option>
            <option value="ESCO">Ensino Superior Completo</option>
            <option value="P">Pós Graduação</option>
            <option value="M">Mestrado</option>
            <option value="D">Doutorado</option>
        </select>
    </div>
    <div class="formacao">
        <label>Formação Acadêmica</label>
        <textarea name="formacao" cols="30" rows="10"></textarea>
    </div>
    <div class="idioma">
        <label for="idiomas">Idiomas</label>
            <select name="idioma" id="opcao_idioma" onchange="optionCheckIdiomas()">
                <option value="ESPANHOL">Espanhol</option>
                <option value="INGLES">Inglês</option>
                <option value="FRANCES">Frances</option>
                <option value="OTR">Outros</option>
            </select>   
    </div>
    <div class="idioma_outros">
            <label>Outros</label>
            <input type="text" name="idioma_outros">
    </div>
    <div class="historico">
        <label>Histórico Profissional</label>
        <textarea name="historico" cols="30" rows="10"></textarea>
    </div>
    <input type="submit" value="Cadastrar">
    </form>
    <a href="index">Sair</a>
</div>  
</div>    
{% endif %}
{% endblock %}

website/templates/cadastro_empresa.html
{% extends 'shared/layout.html' %}
{% block conteudo %}

<div class="area-centro">
<h1>CADASTRO DE EMPRESA</h1>

    <form class ='area-form' action="/cadastro_empresa" method="POST" autocomplete="off">
    {% csrf_token %}
    <div class="razao_social">
    <label for="razao_social">Razão Social</label>
    <input type="text" name="razao_social" id="razao_social" required placeholder="Digite a razão social">
    </div>

    <div class="cnpj">
        <label for="cnpj">CNPJ</label>
        <input type="text" name="cnpj" maxlength="12" required id="cnpj" placeholder="Digite o CNPJ">
    </div>

    <div class="email">
        <label for="email">E-mail</label>
        <input type="email" name="email"  required id="email" placeholder="exemplo@email.com" >
    </div>

    <div class="senha">
        <label for="senha">Senha</label>
        <input type="password" name="senha" id="senha" maxlength="255" minlength="5" required placeholder="***********">
    </div> 

    <div>  
        <input type="submit" value="Cadastrar">
    </div>
    </form>
    </div>
{% endblock %}

website/templates/index.html
{% extends 'shared/layout.html' %}
{% load static %}
{% block conteudo %}
<!--migos aqui é o começo do carrossel-->
<div class="index">
    <div class="alinhar">
        
        
        <div class= "carrossel">
            
            <a class="ant" onclick="plusSlides(-1)">&#10094;</a>
            <a class="prx" onclick="plusSlides(+1)">&#10095;</a>
            <div class= "carousel fade">
            <div class="pageSlc">1 / 3</div>
            <img src="{% static 'image/Carousel1.png' %}" style="width:100%">
        </div>
        
        <div class= "carousel fade">
            <div class="pageSlc">2 / 3</div>
            <img src= "{% static 'image/Carousel2.png' %}" style="width:100%">
        </div>
        
        <div class= "carousel fade">
            <div class="pageSlc">3 / 3</div>
            <img src= "{% static 'image/Caroseul3.png' %}" style="width:100%">
        </div>
        
    </div>
    
    <!--Aqui são os btn -->
    <div class="area-btn"> 
        <span class="btn" onclick="slideAtual(1)"></span> 
            <span class="btn" onclick="slideAtual(2)"></span> 
            <span class="btn" onclick="slideAtual(3)"></span> 
            <!--migos aqui é o final do carrossel-->
        </div>
            
    <div>
        <h2 class="nos"> Integre-se a nós </h2>
    </div>
        
    <div class= 'area-sobre'>
        <table  width="500px">
            <tr><td>
                <p>Somos um projeto de integração de imigrantes no Brasil. Nossa missão é criar um espaço em comum entre você trabalhador e você que é empresa, propiciando vinculos empregaticios com interessados as novas  oportunidades do mercado.</p>
            </td></tr>
            </table>         
    </div>

    <div class="aperto">
        <img src="{% static 'image/aperto.JPG' %}" height="302px" width="50%">
        <img src="{% static 'image/entrevista.jpg' %}" height="300px" width="50%">
    </div>

    <!-- <div class="entrevista"> -->
    <!-- </div> -->
    

    
<div class= 'icons'>

    <div class="ic">
      <img src="{% static 'image/team.png' %}" width="100px">
      <p>Recrutamento eficaz e otimizado</p>
    </div>

    <div class="ic">
        <img src="{% static 'image/promotion.png' %}" >
        <p>Colocação profissional no mercado</p>
    </div>
    
    <div class="ic">
        <img src="{% static 'image/portfolio.png' %}" >
        <p>Parceria com empresas de destaque</p>
    </div> 

    <div class="ic">
        <img src="{% static 'image/resume.png' %}" >
        <p>Acesso rápido e eficaz</p>
    </div>
</div>
    
</div>
</div>
{% endblock %}

website/templates/informacao_candidato.html
{% extends 'shared/layout.html' %}
{% load static%}
{% block conteudo %}
    <div class="area-centro">
        
        <div class="area-form">
            <div class="area-nome">
            <div class="area-foto">
                        <!-- if usado pra dependendo do genero do usuario uma foto diferente sera usada  -->
                        {% if curriculo.candidato.genero == 'F' %}
                        <img src="{% static 'image/iconFeminino.png' %}" class="iconeCandidato">
                        {% elif curriculo.candidato.genero == 'M' %}
                        <img src="{% static 'image/iconMasculino.png' %}" class="iconeCandidato">
                        {% else %}
                        <img src="{% static 'image/iconOutros.png' %}" class="iconeCandidato">
                        {% endif %}
            </div>
            <div>

               
            <h1> {{curriculo.candidato.nome}} {{curriculo.candidato.sobrenome}}</h1>
            </div>
        </div>

            
        <p class="campo-info">
            Pais de origem:
             {{curriculo.candidato.get_pais_de_origem_display}}
        </p>
        <p>Rne: {{curriculo.candidato.rne}}</p>
        <p>Gênero: {{curriculo.candidato.get_genero_display}}</p>
        <p>E-mail: {{curriculo.candidato.email}}</p>
        <p>Telefone: {{curriculo.candidato.telefone}}</p>
        <p>Celular: {{curriculo.candidato.celular}}</p>
        <p>Apresentação: {{curriculo.apresentacao}}</p>
        {% if curriculo.area == "OTR" %}
        <p>Área: {{curriculo.area_outros}}</p>
        {% else %}
        <p>Área: {{curriculo.get_area_display}}</p>
        {% endif %}
        <p>Formação: {{curriculo.formacao}}</p>
        <p>Idioma: {{curriculo.get_idioma_display}}</p>
        <p>Outros Idiomas: {{curriculo.idioma_outros}}</p>
        <p>Histórico Profissional: {{curriculo.historico}}</p>

{% endblock %}

website/templates/pagina_candidato.html
{% comment %} 
    formulario para atualização de dados
    e desativação do perfil

 {% endcomment %}
{% extends 'shared/layout.html' %}
{% block conteudo %}

{% endblock %}